; This file was auto-generated by drush make
core = 7.26

api = 2
projects[drupal][version] = "7.26"

; Modules
projects[views_bulk_operations][version] = "3.2"

projects[admin_menu][version] = "3.0-rc4"

projects[backup_migrate][version] = "2.8"

projects[backup_migrate_files][version] = "1.x-dev"

projects[ctools][version] = "1.3"

projects[bulk_media_upload][version] = "1.x-dev"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cacheflusher][download][type] = ""
projects[cacheflusher][download][url] = ""
projects[cacheflusher][type] = "module"
projects[cacheflusher][version] = "unknown"

projects[devel][version] = "1.3"

projects[entity][version] = "1.3"

projects[entityreference][version] = "1.1"

projects[eva][version] = "1.2"

projects[media][version] = "1.4"

projects[styles][version] = "2.0-alpha8"

projects[filefield_sources][version] = "1.9"

projects[filefield_sources_plupload][version] = "1.1"

projects[fpa][version] = "2.3"

projects[link][version] = "1.2"

projects[media_desk][version] = "1.0-alpha2"

projects[mediabox][version] = "1.x-dev"

projects[module_filter][version] = "2.0-alpha2"

projects[references][version] = "2.1"

projects[pathauto][version] = "1.2"

projects[plupload][version] = "1.6"

projects[styleguide][version] = "1.1"

projects[token][version] = "1.5"

projects[views][version] = "3.7"

; Themes
projects[corporateclean][version] = "1.1"

projects[omega][version] = "4.1"

projects[sky][version] = "3.0-rc1"

